name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      
      - name: Install dependencies    
        run: npm ci
      
      - name: Install playwright dependencies    
        run: npx playwright install    

      - name: Fix vulnerabilities
        run: npm audit fix --force

      - name: Start Backend
        run: npm run server > backend.log 2>&1 &

      - name: Start Frontend
        run: npm start > frontend.log 2>&1 &

      - name: Wait for services to be ready
        run: |
          sleep 10  # Изчаква 10 секунди, за да дадем време на сървърите да стартират
          echo "🔍 Backend log:"
          cat backend.log || echo "❌ Backend log is empty!"
          echo "🔍 Frontend log:"
          cat frontend.log || echo "❌ Frontend log is empty!"
          npx wait-on http://localhost:3000
