name: deploy

on:
  push:
    branches: [ "production" ]

jobs:
  deploy_backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: JorgeLNJunior/render-deploy@v1.4.4
        with:
          service_id: ${{ secrets.SERVICE_BACKEND_ID }}
          api_key: ${{ secrets.API_TOKEN }}
          wait_deploy: true 

  deploy_frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: JorgeLNJunior/render-deploy@v1.4.4
        with:
          service_id: ${{ secrets.SERVICE_FRONTEND_ID }}
          api_key: ${{ secrets.API_TOKEN }}
          wait_deploy: true  
